const cities = [
  { label: "Afganistán" },
  { label: "Albania" },
  { label: "Alemania" },
  { label: "Andorra" },
  { label: "Angola" },
  { label: "Anguilla" },
  { label: "Antártida" },
  { label: "Antigua y Barbuda" },
  { label: "Antillas Holandesas" },
  { label: "Arabia Saudí" },
  { label: "Argelia" },
  { label: "Argentina" },
  { label: "Armenia" },
  { label: "Aruba" },
  { label: "Australia" },
  { label: "Austria" },
  { label: "Azerbaiyán" },
  { label: "Bahamas" },
  { label: "Bahrein" },
  { label: "Bangladesh" },
  { label: "Barbados" },
  { label: "Bélgica" },
  { label: "Belice" },
  { label: "Benin" },
  { label: "Bermudas" },
  { label: "Bielorrusia" },
  { label: "Birmania" },
  { label: "Bolivia" },
  { label: "Bosnia y Herzegovina" },
  { label: "Botswana" },
  { label: "Brasil" },
  { label: "Brunei" },
  { label: "Bulgaria" },
  { label: "Burkina Faso" },
  { label: "Burundi" },
  { label: "Bután" },
  { label: "Cabo Verde" },
  { label: "Camboya" },
  { label: "Camerún" },
  { label: "Canadá" },
  { label: "Chad" },
  { label: "Chile" },
  { label: "China" },
  { label: "Chipre" },
  { label: "Ciudad del Vaticano (Santa Sede)" },
  { label: "Colombia" },
  { label: "Comores" },
  { label: "Congo" },
  { label: "Congo, República Democrática del" },
  { label: "Corea" },
  { label: "Corea del Norte" },
  { label: "Costa de Marfíl" },
  { label: "Costa Rica" },
  { label: "Croacia (Hrvatska)" },
  { label: "Cuba" },
  { label: "Dinamarca" },
  { label: "Djibouti" },
  { label: "Dominica" },
  { label: "Ecuador" },
  { label: "Egipto" },
  { label: "El Salvador" },
  { label: "Emiratos Árabes Unidos" },
  { label: "Eritrea" },
  { label: "Eslovenia" },
  { label: "selected>España" },
  { label: "Estados Unidos" },
  { label: "Estonia" },
  { label: "Etiopía" },
  { label: "Fiji" },
  { label: "Filipinas" },
  { label: "Finlandia" },
  { label: "Francia" },
  { label: "Gabón" },
  { label: "Gambia" },
  { label: "Georgia" },
  { label: "Ghana" },
  { label: "Gibraltar" },
  { label: "Granada" },
  { label: "Grecia" },
  { label: "Groenlandia" },
  { label: "Guadalupe" },
  { label: "Guam" },
  { label: "Guatemala" },
  { label: "Guayana" },
  { label: "Guayana Francesa" },
  { label: "Guinea" },
  { label: "Guinea Ecuatorial" },
  { label: "Guinea-Bissau" },
  { label: "Haití" },
  { label: "Honduras" },
  { label: "Hungría" },
  { label: "India" },
  { label: "Indonesia" },
  { label: "Irak" },
  { label: "Irán" },
  { label: "Irlanda" },
  { label: "Isla Bouvet" },
  { label: "Isla de Christmas" },
  { label: "Islandia" },
  { label: "Islas Caimán" },
  { label: "Islas Cook" },
  { label: "Islas de Cocos o Keeling" },
  { label: "Islas Faroe" },
  { label: "Islas Heard y McDonald" },
  { label: "Islas Malvinas" },
  { label: "Islas Marianas del Norte" },
  { label: "Islas Marshall" },
  { label: "Islas menores de Estados Unidos" },
  { label: "Islas Palau" },
  { label: "Islas Salomón" },
  { label: "Islas Svalbard y Jan Mayen" },
  { label: "Islas Tokelau" },
  { label: "Islas Turks y Caicos" },
  { label: "Islas Vírgenes (EEUU)" },
  { label: "Islas Vírgenes (Reino Unido)" },
  { label: "Islas Wallis y Futuna" },
  { label: "Israel" },
  { label: "Italia" },
  { label: "Jamaica" },
  { label: "Japón" },
  { label: "Jordania" },
  { label: "Kazajistán" },
  { label: "Kenia" },
  { label: "Kirguizistán" },
  { label: "Kiribati" },
  { label: "Kuwait" },
  { label: "Laos" },
  { label: "Lesotho" },
  { label: "Letonia" },
  { label: "Líbano" },
  { label: "Liberia" },
  { label: "Libia" },
  { label: "Liechtenstein" },
  { label: "Lituania" },
  { label: "Luxemburgo" },
  { label: "Macedonia, Ex-República Yugoslava de" },
  { label: "Madagascar" },
  { label: "Malasia" },
  { label: "Malawi" },
  { label: "Maldivas" },
  { label: "Malí" },
  { label: "Malta" },
  { label: "Marruecos" },
  { label: "Martinica" },
  { label: "Mauricio" },
  { label: "Mauritania" },
  { label: "Mayotte" },
  { label: "México" },
  { label: "Micronesia" },
  { label: "Moldavia" },
  { label: "Mónaco" },
  { label: "Mongolia" },
  { label: "Montserrat" },
  { label: "Mozambique" },
  { label: "Namibia" },
  { label: "Nauru" },
  { label: "Nepal" },
  { label: "Nicaragua" },
  { label: "Níger" },
  { label: "Nigeria" },
  { label: "Niue" },
  { label: "Norfolk" },
  { label: "Noruega" },
  { label: "Nueva Caledonia" },
  { label: "Nueva Zelanda" },
  { label: "Omán" },
  { label: "Países Bajos" },
  { label: "Panamá" },
  { label: "Papúa Nueva Guinea" },
  { label: "Paquistán" },
  { label: "Paraguay" },
  { label: "Perú" },
  { label: "Pitcairn" },
  { label: "Polinesia Francesa" },
  { label: "Polonia" },
  { label: "Portugal" },
  { label: "Puerto Rico" },
  { label: "Qatar" },
  { label: "Reino Unido" },
  { label: "República Centroafricana" },
  { label: "República Checa" },
  { label: "República de Sudáfrica" },
  { label: "República Dominicana" },
  { label: "República Eslovaca" },
  { label: "Reunión" },
  { label: "Ruanda" },
  { label: "Rumania" },
  { label: "Rusia" },
  { label: "Sahara Occidental" },
  { label: "Saint Kitts y Nevis" },
  { label: "Samoa" },
  { label: "Samoa Americana" },
  { label: "San Marino" },
  { label: "San Vicente y Granadinas" },
  { label: "Santa Helena" },
  { label: "Santa Lucía" },
  { label: "Santo Tomé y Príncipe" },
  { label: "Senegal" },
  { label: "Seychelles" },
  { label: "Sierra Leona" },
  { label: "Singapur" },
  { label: "Siria" },
  { label: "Somalia" },
  { label: "Sri Lanka" },
  { label: "St Pierre y Miquelon" },
  { label: "Suazilandia" },
  { label: "Sudán" },
  { label: "Suecia" },
  { label: "Suiza" },
  { label: "Surinam" },
  { label: "Tailandia" },
  { label: "Taiwán" },
  { label: "Tanzania" },
  { label: "Tayikistán" },
  { label: "Territorios franceses del Sur" },
  { label: "Timor Oriental" },
  { label: "Togo" },
  { label: "Tonga" },
  { label: "Trinidad y Tobago" },
  { label: "Túnez" },
  { label: "Turkmenistán" },
  { label: "Turquía" },
  { label: "Tuvalu" },
  { label: "Ucrania" },
  { label: "Uganda" },
  { label: "Uruguay" },
  { label: "Uzbekistán" },
  { label: "Vanuatu" },
  { label: "Venezuela" },
  { label: "Vietnam" },
  { label: "Yemen" },
  { label: "Yugoslavia" },
  { label: "Zambia" },
  { label: "Zimbabue" },
];

export default cities;
